Repository evanugarte/EveryReceipt, pull requests merged in 2019-05, with the labels that each got.

#37 Added File Page + Form Handling
  src/actions/expenseActions.js
  src/actions/types.js
  src/components/Common/ExpenseList.js
  src/components/Common/FormFields.js
  src/components/Common/styles.js
  src/components/HomeScreen/AddButton.js
  src/components/HomeScreen/ExpenseItem.js
  src/components/HomeScreen/HomeButton.js
  src/components/HomeScreen/HomeScreen.js
  src/components/ItemEdit/ItemEdit.js
  src/components/ItemEntry/ManualAddScreen.js
  src/components/Profile/AllExpenses.js
  src/components/Profile/Profile.js
  src/navigator/Home.js
  src/reducers/expenseReducer.js
Labels: enhancement

#39 UI improvements
  .gitignore
  src/components/Common/styles.js
  src/components/HomeScreen/HomeScreen.js
  src/components/ItemEntry/ManualAddScreen.js
  src/components/SearchScreen/SearchBar.js
  src/config/.gitignore
  src/navigator/LoggedIn.js
  yarn.lock
Labels: bug, enhancement

#44 Added Sorting Expenses by Date
  src/actions/expenseActions.js
  src/components/Auth/LoginScreen.js
  src/components/Common/FormFields.js
  src/components/ItemEdit/ItemEdit.js
  src/config/.gitignore
Labels: enhancement

#51 Added Partial Matching to Store Name + FormFields Revert
  src/actions/expenseActions.js
  src/components/Auth/LoginScreen.js
  src/components/Auth/SignUpScreen.js
  src/components/Common/FormFields.js
  src/components/Common/styles.js
  src/components/HomeScreen/HomeScreen.js
Labels: bug, enhancement

#52 Modal fixes
  src/components/Common/styles.js
  src/components/HomeScreen/ExpenseItem.js
  src/components/HomeScreen/HomeScreen.js
Labels: enhancement

#50 OCR logic corrected
  src/components/Common/FormFields.js
Labels: bug

#55 Added View Titles + Prop Type Handling
  App.js
  src/components/Common/FormFields.js
  src/components/HomeScreen/HomeScreen.js
Labels: enhancement
